// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Candidate struct {
	ID        string    `json:"_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type NewCandidate struct {
	Name string `json:"name"`
}

type NewCandidateDatabase struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}
